# Generated by Django 5.1.1 on 2024-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pais', models.CharField(help_text='Código do país (ex: +55)', max_length=3)),
                ('telefone', models.CharField(help_text='Número do telefone no formato XXXXX-XXXX', max_length=15)),
            ],
        ),
    ]
